import type { GenerationResult } from '../journey-storage'

export const testGenerationResult: GenerationResult = {
  preferences: {
    routePackId: 'wukang-hunan',
    startPoiId: 'auto',
    durationMinutes: 180,
    companion: 'solo',
    interests: ['建筑细节'],
    genre: 'mystery',
    taskIntensity: 'standard',
    budgetCny: 50,
    indoorPreference: 'balanced',
    photoTasksEnabled: true,
    puzzleTasksEnabled: true,
    storyExplorationRatio: 60,
  },
  routePlan: {
    routeId: 'route_test',
    routePackId: 'wukang-hunan',
    selectedPois: [
      {
        id: 'mock_wk_01',
        routePackId: 'wukang-hunan',
        name: '开发模拟节点 A1',
        shortName: '模拟 A1',
        address: '开发测试地址（不对应真实地点）',
        longitude: 121.43,
        latitude: 31.21,
        category: 'mock_outdoor',
        indoor: false,
        publicAccess: true,
        estimatedCostCny: 0,
        stayMinutes: 15,
        walkMinutes: 5,
        tags: ['development'],
        moodTags: ['quiet'],
        storyHooks: ['fiction-only'],
        taskHooks: ['observe-detail'],
        observationAnchors: ['shape'],
        safetyNotes: ['remain-in-public-space'],
        verificationStatus: 'mock',
        verifiedAt: null,
        sourceUrls: [],
        fallbackPoiIds: [],
      },
    ],
    alternativePois: [],
    routeSegments: [],
    totalWalkMeters: 1800,
    totalWalkMinutes: 28,
    totalStayMinutes: 60,
    totalEstimatedMinutes: 88,
    estimatedCostCny: 0,
    degraded: false,
  },
  story: {
    blueprint: {
      storyId: 'story_test',
      title: '失物电台测试档案',
      subtitle: '沿着一段没有登记的频率前行',
      genre: 'mystery',
      role: '临时频率记录员',
      mission: '确认三次重复出现的编号',
      premise: '一段用于自动化测试的虚构城市暗线。',
      actStructure: [
        {
          id: 'act_1',
          title: '收到讯号',
          summary: '发现第一条线索。',
          objective: '确认编号。',
          poiIds: ['mock_wk_01'],
        },
      ],
      characters: [],
      clueChain: [],
      items: [],
      branchPlan: [],
      sideQuestPlan: [],
      endingPlan: [
        {
          id: 'ending_1',
          title: '保留频率',
          condition: '完成观察',
          summary: '完成测试结局。',
          hidden: false,
        },
      ],
      fictionNotice: '本故事为虚构内容，Mock POI 不可用于真实导航。',
      contentWarnings: ['注意交通与公共空间规则。'],
    },
    storyGraph: {
      entryNodeId: 'node_intro',
      nodes: [
        {
          id: 'node_intro',
          poiId: 'mock_wk_01',
          type: 'intro',
          title: '收到讯号',
          storyText: '这段完整剧情不应出现在预览页面。',
          arrivalText: null,
          task: {
            id: 'task_1',
            type: 'observe',
            title: '观察编号',
            instructions: '只观察公共区域。',
            required: true,
            estimatedMinutes: 3,
            observationAnchors: ['shape'],
          },
          choices: [],
          rewards: { scores: {}, clues: [], items: [], flags: {} },
          requiredState: {
            minimumScores: {},
            clues: [],
            items: [],
            flags: {},
          },
          next: null,
          fallbackNext: null,
          estimatedMinutes: 5,
          safetyNotice: null,
        },
      ],
      endings: [
        {
          id: 'ending_1',
          title: '保留频率',
          summary: '完成测试结局。',
          requiredState: {
            minimumScores: {},
            clues: [],
            items: [],
            flags: {},
          },
        },
      ],
      hiddenEnding: null,
      stateDefinition: {
        initialEffectScores: {
          truth: 0,
          memory: 0,
          empathy: 0,
          courage: 0,
          connection: 0,
        },
        initialClues: [],
        initialItems: [],
        initialFlags: {},
      },
    },
    fallbackUsed: true,
    fallbackReason: 'STORY_GRAPH_INVALID',
  },
  savedAt: '2026-07-26T08:00:00.000Z',
}
